chore(deps): update Sentry SDK to v7.16.0 (#99)
Bumps scripts/update-sentry-sdk.sh from 7.15.0 to 7.16.0.

Auto-generated by a [dependency
updater](https://github.com/getsentry/github-workflows/blob/main/.github/workflows/updater.yml).
## Changelog
### 7.16.0

#### Features

- Add meta option to attach ANR thread dumps
([#3791](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3791))

#### Fixes

- Cache parsed Dsn
([#3796](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3796))
- fix invalid profiles when the transaction name is empty
([#3747](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3747))
- Deprecate `enableTracing` option
([#3777](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3777))
- Vendor `java.util.Random` and replace `java.security.SecureRandom`
usages
([#3783](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3783))
- Fix potential ANRs due to NDK scope sync
([#3754](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3754))
- Fix potential ANRs due to NDK System.loadLibrary calls
([#3670](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3670))
- Fix slow `Log` calls on app startup
([#3793](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3793))
- Fix slow Integration name parsing
([#3794](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3794))
- Session Replay: Reduce startup and capture overhead
([#3799](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3799))
- Load lazy fields on init in the background
([#3803](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3803))
- Replace setOf with HashSet.add
([#3801](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3801))

#### Breaking changes

- The method `addIntegrationToSdkVersion(Ljava/lang/Class;)V` has been
removed from the core (`io.sentry:sentry`) package. Please make sure all
of the packages (e.g. `io.sentry:sentry-android-core`,
`io.sentry:sentry-android-fragment`, `io.sentry:sentry-okhttp` and
others) are all aligned and using the same version to prevent the
`NoSuchMethodError` exception.

### 7.16.0-alpha.1

#### Features

- Add meta option to attach ANR thread dumps
([#3791](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3791))

#### Fixes

- Cache parsed Dsn
([#3796](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3796))
- fix invalid profiles when the transaction name is empty
([#3747](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3747))
- Deprecate `enableTracing` option
([#3777](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3777))
- Vendor `java.util.Random` and replace `java.security.SecureRandom`
usages
([#3783](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3783))
- Fix potential ANRs due to NDK scope sync
([#3754](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3754))
- Fix potential ANRs due to NDK System.loadLibrary calls
([#3670](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3670))
- Fix slow `Log` calls on app startup
([#3793](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3793))
- Fix slow Integration name parsing
([#3794](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3794))
- Session Replay: Reduce startup and capture overhead
([#3799](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/3799))

Co-authored-by: GitHub <noreply@github.com>